# Generated by Django 4.1.6 on 2023-02-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=100)),
                ("Author", models.CharField(max_length=50)),
                ("Isbn", models.CharField(max_length=100)),
                ("Publisher", models.CharField(max_length=100)),
            ],
        ),
    ]
